### ISSUE TITLE
android (PowerVR GPU)

### ISSUE THREAD

**Issue by havlenapetr** [omcfadde/dante#17]
Hi, on my device I am getting this error:

----- R_InitOpenGL -----
I/Doom    (23790): GLimp_Init - start
I/Doom    (23790): GL parms: width(800), height(480)
D/libEGL  (23790): loaded /system/lib/egl/libGLES_android.so
D/libEGL  (23790): loaded /vendor/lib/egl/libEGL_POWERVR_SGX540_120.so
D/libEGL  (23790): loaded /vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so
D/libEGL  (23790): loaded /vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so
I/Doom    (23790): Using 8/8/8 Color bits, 8 Alpha bits, 24 depth, 8 stencil display.
I/Doom    (23790): Using format(5) for window
I/Doom    (23790): GLimp_ActivateContext - start
I/Doom    (23790): Fetching EGL surface and context
I/Doom    (23790): Surface parms: width(800), height(480)
I/Doom    (23790): GLimp_ActivateContext - end
I/Doom    (23790): GLimp_Init - end
I/Doom    (23790): X..GL_ARB_multitexture not found
I/Doom    (23790): X..GL_ARB_texture_env_combine not found
I/Doom    (23790): X..GL_ARB_texture_cube_map not found
I/Doom    (23790): X..GL_ARB_texture_env_dot3 not found
I/Doom    (23790): X..GL_ARB_texture_env_add not found
I/Doom    (23790): X..GL_ARB_texture_non_power_of_two not found
I/Doom    (23790): X..GL_EXT_texture_lod not found
I/Doom    (23790): X..GL_1.4_texture_lod_bias not found
I/Doom    (23790): X..GL_EXT_shared_texture_palette not found
I/Doom    (23790): X..GL_EXT_texture3D not found
I/Doom    (23790): X..GL_ARB_vertex_buffer_object not found
I/Doom    (23790): X..GL_ARB_vertex_program not found
I/Doom    (23790): X..GL_ARB_fragment_program not found
I/Doom    (23790): X..GL_ARB_shading_language_100 not found
I/Doom    (23790): ---------- R_GLSL_Init ----------
I/Doom    (23790): Not available.
I/Doom    (23790): ----- R_ReloadGLSLPrograms -----
I/Doom    (23790): gl2progs/interaction.vert
I/Doom    (23790): filesystem: switching to pure mode will require a restart. 'gl2progs/interaction.vert' loaded from directory.
I/Doom    (23790): 
I/Doom    (23790): gl2progs/interaction.frag
I/Doom    (23790): 
I/Doom    (23790): VS:
I/Doom    (23790): Success.
I/Doom    (23790): 
I/Doom    (23790): FS:
I/Doom    (23790): Compile failed.
I/Doom    (23790): ERROR: 0:23: 'vec2' : No precision defined for this type
I/Doom    (23790): ERROR: 0:24: 'vec2' : No precision defined for this type
I/Doom    (23790): ERROR: 0:25: 'vec2' : No precision defined for this type
I/Doom    (23790): ERROR: 0:26: 'vec4' : No precision defined for this type
I/Doom    (23790): ERROR: 0:27: 'vec4' : No precision defined for this type
I/Doom    (23790): ERROR: 0:28: 'vec3' : No precision defined for this type
I/Doom    (23790): ERROR: 0:32: 'vec3' : No precision defined for this type
I/Doom    (23790): ERROR: 0:41: 'vec4' : No precision defined for this type
I/Doom    (23790): ERROR: 0:42: 'vec4' : No precision defined for this type
I/Doom    (23790): ERROR: 0:50: 'float' : No precision defined for this type
I/Doom    (23790): ERROR: 0:53: 'vec3' : No precision defined for this type
I/Doom    (23790): ERROR: 0:58: 'vec3' : No precision defined for this type
I/Doom    (23790): ERROR: 0:59: 'vec3' : No precision defined for this type
I/Doom    (23790): ERROR: 0:62: 'float' : No precision defined for this type
I/Doom    (23790): ERROR: 0:67: 'vec3' : No precision defined for this type
I/Doom    (23790): ERROR: 0:68: 'vec3' : No precision defined for this type
I/Doom    (23790): ERROR: 0:69: 'vec3' : No precision defined for this type

i have yours gl2progs/ in base dir and it looks like everything works, except: glGetProgramiv(shaderProgram->program, GL_LINK_STATUS, &linked); because linked is 0, do you know what it means please??

**Comment by omcfadde** [comment]
The latest _gl2progs_ have precision specifiers for floating point types, however, this _may_ not be enough for SGX. It may require a precision specifier on every vector, though I hope not.

Please retry with the latest _gl2progs_; I have updated those last night.

**Comment by havlenapetr** [comment]
thanks, latest gl2progs looks good

**Comment by omcfadde** [comment]
Awesome, I hope I can also get the performance up a bit on SGX and other embedded GPUs. Right now I'm using _highp_ precision which is probably overkill in a few situations.

Glad to hear the latest _gl2progs_ solved the issue for you. :-)

**Comment by havlenapetr** [comment]
It is great, my port is working on device, but now app is stuck somewhere in common->Frame(); so I can't say how much fps I am getting, but I will debug it
