### ISSUE TITLE
dante.mobi Site Down?

### ISSUE THREAD

**Issue by thommoboy** [omcfadde/dante#31]
hey is the site down? i have an error but i don't want to post it until i get the new version :/

**Comment by omcfadde** [comment]
http://www.downforeveryoneorjustme.com/dante.mobi

It's just you. http://dante.mobi is up.

**Comment by eberan** [comment]
It seems down to me, including http://www.downforeveryoneorjustme.com/dante.mobi
Is there any other location the glsl es shaders are uploaded? :/

**Comment by clort81** [comment]
In case someone still is looking, good to have them findable.
[pak000_gl2progs.pk4.zip](https://github.com/omcfadde/dante/files/6887903/pak000_gl2progs.pk4.zip)

These are GPL 3 licensed.
