### ISSUE TITLE
can't link gl2progs

### ISSUE THREAD

**Issue by havlenapetr** [omcfadde/dante#34]
I can't link gl2progs on osx desktop, gpu: NVIDIA GeForce 9400M. Do you use glsl backend on your desktop or are you using arb backend?

gl2progs/interaction.vertfilesystem: switching to pure mode will require a restart. 'gl2progs/interaction.vert' loaded from directory.

gl2progs/interaction.frag
VS:
ERROR: 0:18: '' :  Version number not supported by GL2
ERROR: 0:21: 'precision' : syntax error syntax error
ERROR: Parser found no code to compile in source strings.

FS:
ERROR: 0:18: '' :  Version number not supported by GL2
ERROR: 0:21: 'precision' : syntax error syntax error
ERROR: Parser found no code to compile in source strings.

**Comment by kphillisjr** [comment]
Can you please include the full Dante log? also, Which revision are you using?

**Comment by havlenapetr** [comment]
I am using branch es2

Running…
DOOM 1.3.1.1304-debug MacOSX-universal Aug 30 2012 22:36:15
loopback
IP: 10.10.101.8
NetMask: 255.255.255.0
doom using MMX & SSE & SSE2 & SSE3 for SIMD processing
enabled Flush-To-Zero mode
enabled Denormals-Are-Zero mode
------ Initializing File System ------
Loaded pk4 /Users/petr/Library/Application Support/Doom 3/base/pak000.pk4 with checksum 0xd4eacbd8
Loaded pk4 /Users/petr/Library/Application Support/Doom 3/base/pak001.pk4 with checksum 0x40244be0
Loaded pk4 /Users/petr/Library/Application Support/Doom 3/base/pak002.pk4 with checksum 0xe87384bf
Loaded pk4 /Users/petr/Library/Application Support/Doom 3/base/pak003.pk4 with checksum 0xcd79d028
Loaded pk4 /Users/petr/Library/Application Support/Doom 3/base/pak004.pk4 with checksum 0x6bd412fd
Loaded pk4 /Users/petr/Library/Application Support/Doom 3/base/pak005.pk4 with checksum 0x3e1a5ae3
Loaded pk4 /Users/petr/Library/Application Support/Doom 3/base/pak006.pk4 with checksum 0x23e293a0
Loaded pk4 /Users/petr/Library/Application Support/Doom 3/base/pak007.pk4 with checksum 0x7beef956
Current search path:
/Users/petr/Library/Application Support/Doom 3/base
/Users/petr/Library/Application Support/Doom 3/base/pak007.pk4 (54 files)
/Users/petr/Library/Application Support/Doom 3/base/pak006.pk4 (59 files)
/Users/petr/Library/Application Support/Doom 3/base/pak005.pk4 (74 files)
/Users/petr/Library/Application Support/Doom 3/base/pak004.pk4 (10267 files)
/Users/petr/Library/Application Support/Doom 3/base/pak003.pk4 (4681 files)
/Users/petr/Library/Application Support/Doom 3/base/pak002.pk4 (8797 files)
/Users/petr/Library/Application Support/Doom 3/base/pak001.pk4 (8972 files)
/Users/petr/Library/Application Support/Doom 3/base/pak000.pk4 (3970 files)
/Users/petr/projects/app/android/adoom3/idtech4/neo/sys/osx/build/Debug/base
game DLL: 0x0 in pak: 0x0
Addon pk4s:

## file system initialized.

## ----- Initializing Decls -----

------- Initializing renderSystem --------

## renderSystem initialized.

5206 strings read from strings/english.lang
Couldn't open journal files
execing editor.cfg
execing default.cfg
execing DoomConfig.cfg
couldn't exec autoexec.cfg
5206 strings read from strings/english.lang
----- Initializing Sound System ------

## sound system initialized.

----- R_InitOpenGL -----
Initializing OpenGL subsystem
  fullscreen: no
 800 480 Windowed
ok

## FIXME: Sys_UnfadeScreen

------- Input Initialization -------
4 sound device(s)
  0: ID 264, Built-in Input - Apple Inc.
  1: ID 266, Built-in Output - Apple Inc.
  2: ID 260, Soundflower (2ch) - ma++ ingalls for Cycling '74
  3: ID 257, Soundflower (16ch) - ma++ ingalls for Cycling '74
select default device, ID 266
current nominal rate: 44100
current frame size: 512
frame size allowed range: 14 9216
setting frame size to: 4096
using stereo channel IDs 1 2
...using GL_ARB_multitexture
...using GL_ARB_texture_env_combine
...using GL_ARB_texture_cube_map
...using GL_ARB_texture_env_dot3
...using GL_ARB_texture_env_add
...using GL_ARB_texture_non_power_of_two
X..GL_OES_compressed_ETC1_RGB8_texture not found
X..GL_IMG_texture_compression_pvrtc not found
...using GL_1.4_texture_lod_bias
X..GL_EXT_shared_texture_palette not found
X..GL_EXT_texture3D not found
...using GL_ARB_vertex_buffer_object
...using GL_ARB_vertex_program
...using GL_ARB_fragment_program
...using GL_ARB_shading_language_100
---------- R_GLSL_Init ----------

## Available.

----- R_ReloadGLSLPrograms -----
gl2progs/interaction.vertfilesystem: switching to pure mode will require a restart. 'gl2progs/interaction.vert' loaded from directory.

gl2progs/interaction.frag
VS:
ERROR: 0:18: '' :  Version number not supported by GL2
ERROR: 0:21: 'precision' : syntax error syntax error
ERROR: Parser found no code to compile in source strings.

FS:
ERROR: 0:18: '' :  Version number not supported by GL2
ERROR: 0:21: 'precision' : syntax error syntax error
ERROR: Parser found no code to compile in source strings.

TODO: Sys_SetClipboardData

---

ERROR: R_LinkGLSLShader: program failed to link

---

Sys_Error: Error during initialization

**Comment by omcfadde** [comment]
I am not officially supporting OSX or Windows, so you're somewhat on your own there if you want to add OSX support back into the tree. However in this case it's quite clear that the OpenGL driver is failing to compile the shaders; most likely because you're attempting to use shaders written for OpenGL ES2.0 with a desktop OpenGL 2.x profile.

It should be possible to adjust the `#version` token and you could for example remove all the `precision mediump float;` statements; they are an optimization telling the driver that it does not need to use the highest available precision and not critical for functionality.

**Comment by havlenapetr** [comment]
ok, thanks for info. I thought that others are using glsl on desktop too and nvidia gpu is ordinary hw on these days PCs, nevermind I will solve it. Than maybe you will be able to merge my osx support into main tree
