### ISSUE TITLE
Data error

### ISSUE THREAD

**Issue by havlenapetr** [omcfadde/dante#35]
I've compiled doom3 master branch on my mac and I am getting weird error with datas: Missing 'anim' key on 'idCameraAnim_marscity_cinematic_cam_72'. It is weird, because on my android device game is running fine.

**Comment by omcfadde** [comment]
This is pretty difficult to debug without the game log output and also OSX isn't officially supported...

**Comment by omcfadde** [comment]
Closing for now due to inactivity; you may reopen but please provide detailed and complete logs otherwise it's simply impossible for me to debug or provide suggestions.
