### ISSUE TITLE
Windows master/glsl branches code compilation errors

### ISSUE THREAD

**Issue by bryansee** [omcfadde/dante#38]
I am trying to compile the code from the master and glsl branches on the Windows platform, but I'm getting compilation errors stemming from the glx.h file not found, and so forth, despite getting the jpeg-8 source code.

**Comment by kphillisjr** [comment]
Windows support was removed by commit 0368f2b73269764189ed38b6fc4a94d3c9b2dc6c

So if you wish to fix this... it will require either reverting this commit, or implementing the system interfaces using a cross-platform toolkit that is osx/windows compatible.

**Comment by omcfadde** [comment]
Dante does not support building or running on Windows. Closing issue.
