### ISSUE TITLE
problem running with OpenGL

### ISSUE THREAD

**Issue by ridowan007** [omcfadde/dante#39]
I am trying to run the engine. My PC's specification is here http://paste.ubuntu.com/1215030/

As I am using AMD fglrx driver, compiling with EGL don't work out for me. So I try to use opengl build by setting TARGET_OPENGL in site.conf file to 1. It compiles ok; but when I tried to run it, the screen resolution changed and for 1/2 second screen flicker, then the code exit. But the resolution stays low as well(That's probably a fglrx issue, crashed opengl apps always do it). The terminal output is here http://paste.ubuntu.com/1215042/

By analyzing, it seems the problem is causing by GL_EnableVertexAttribArray call(my wild guess). Also none of the gl2progs/ file seems to found. When I run the program with gdb, it gives one additional hint -

using GLSL renderSystem
WARNING: Invalid compressed internal format

WARNING: Invalid uncompressed internal format

GL_EnableVertexAttribArray: unbound attribute index

Program received signal SIGILL, Illegal instruction.
0x0000000000484ae8 in GL_EnableVertexAttribArray (index=<optimized out>) at renderer/tr_backend.cpp:244
244                     common->Printf("GL_EnableVertexAttribArray: unbound attribute index\n");
(gdb)

I am not sure what is causing it. I compiled and run the dhewm3, and that's seems to run perfectly well. Also I have the original doom3's binary and that's also seems ok. May be that's a glsl issue. A 'glxinfo' of my system is here http://paste.ubuntu.com/1215065/

**Comment by kphillisjr** [comment]
First off, in your log I spotted the following...

```
----- R_ReloadGLSLPrograms -----
gl2progs/interaction.vert: File not found
gl2progs/interaction.frag: File not found
gl2progs/shadow.vert: File not found
gl2progs/shadow.frag: File not found
gl2progs/default.vert: File not found
gl2progs/default.frag: File not found
gl2progs/zfill.vert: File not found
gl2progs/zfill.frag: File not found
```

This means you are missing [gl2progs](https://github.com/omcfadde/gl2progs). 

checkout a copy of that into the following path:
/home/ridowan/.doom3/base/gl2progs

**Comment by omcfadde** [comment]
Thanks @kphillisjr, this will resolve the issue @ridowan007 experienced. Closing (although I should add a check to the GLSL backend to avoid further situations such as this one.)
