### ISSUE TITLE
Add support for Android tablet devices

### ISSUE THREAD

**Issue by omcfadde** [omcfadde/dante#6]

**Comment by omcfadde** [comment]
90% complete, 90% remaining...

**Comment by kkszysiu** [comment]
Damn I just started to make the same thing! :D

**Comment by omcfadde** [comment]
You're welcome to go ahead. I'm running into some weird problems with thread synchronization and memcpy() bugs that shouldn't be possible... you might very well complete the work before me.

**Comment by kkszysiu** [comment]
I don't know yet what I'm heading atm... I prepared scripts to compile everything and for now I'm stuck there. I will work on NativeActivity wrapper now :)

**Comment by kkszysiu** [comment]
Some works done. Far from perfect but...

https://plus.google.com/u/0/108396638562408971291/posts/MyFmnGBPPec :)

**Comment by omcfadde** [comment]
Nice work! :-) Please push the code onto Github so that I can take a look at improving it and merging into Dante.

**Comment by kkszysiu** [comment]
I will try to clean up those mess soon and upload it on different branch for now.

BTW. I have more than 30 fps on my DHD on test_box map but it took almost 3 minutes or more to load it :D

**Comment by omcfadde** [comment]
Great, thanks. It's okay if the code isn't perfectly tidy. 30 fps is very respectable, but I believe this can be improved upon. I have a few ideas.

**Comment by kkszysiu** [comment]
Yeah, I know... youre GLES 2.0 master here :D There's still a lot to do but it is at least something... code cleaning is required mostly because hardcoded paths etc... but I will try to fix it soon and I will prepare readme for all those who want to compile it :)

https://plus.google.com/u/0/108396638562408971291/posts/6dJwiANyC66

**Comment by havlenapetr** [comment]
I wrote native android makefiles into your project: https://github.com/havlenapetr/idtech4 for ndk build

**Comment by kkszysiu** [comment]
Is it working? I didnt check your code yet... I'm still using scons to build everything. Do you have working sound?

**Comment by kkszysiu** [comment]
I need to work on sound soon... we should use native OpenSL support on Android instead of OpenAL if it will be possible but for now we could use OpenAL if we don't have anything else. For now Im using null sound because I don't wanted to load huge sound sample files just yet.

**Comment by kkszysiu** [comment]
https://github.com/kkszysiu/dante/tree/android/android here you go :)

**Comment by omcfadde** [comment]
Very nice, thanks. :-) There are of course a couple of minor clean up issues (white space and line endings etc) but that's nothing I can't take care of while merging.

You've definitely secured yourself a place on the Dante credits GUI screen (once that's implemented!) Until then, I'm thinking of adding an `AUTHORS' file like most of the GNU projects.

**Comment by kkszysiu** [comment]
Did you compiled it successfuly?

**Comment by havlenapetr** [comment]
I have working openal impl for android: https://github.com/havlenapetr/openal but you must compile it against android full source code and than use it like prebuilt with ndk.

**Comment by havlenapetr** [comment]
and yes compilation works, I am debugging app right now

**Comment by kkszysiu** [comment]
Yes, OpenAL works but it doesn't have support for fixed-point decoding. The same as vorbis so you will have propably huge decrease in performance on sound... so best choice is to reimplement whole sound soundsystem using libtremor (fixed-point libvorbis equvalent) and OpenSL (native Android sound implementation, prepared for low-latency, embedded purposes).

**Comment by havlenapetr** [comment]
I know, but OpenSL is implemented only on newer devices. BTW doom code is pretty hungry in performance too

**Comment by kkszysiu** [comment]
Yeah so we don't need support for older devices. Doom 3 won't work on them anyway... OpenSL is introduced in Android 2.3, the same as NativeActivity so Android 2.3 should be minimal requirement (We will still need ARMv7 CPU and NEON set on device anyway (and most of Android 2.3 powered devices has them, excluding chinese tablets for 20$), without it there's no even chances that Doom 3 will work smoothly :))

**Comment by havlenapetr** [comment]
right, my port works on native activity too, I will push it and start working on OpenSL backend

**Comment by kkszysiu** [comment]
BTW did you tried to build Doom 3 using my code? I want to be sure my how-to in README is easy to understand...

**Comment by havlenapetr** [comment]
nop, i will try, I am at work right now :-)

**Comment by omcfadde** [comment]
kkszysiu, it's a good idea to use `set -e' in your Bash script, e.g.

```
#!/bin/bash
set -e
```

This means that your script will not continue if a command fails; it has some exceptions, but they are there for good reason. See `man bash'

```
-e      Exit immediately if a pipeline (which may consist of a single simple
        command), a subshell command enclosed in parentheses, or one of the
        commands executed as part of a command list enclosed by braces (see
        SHELL GRAMMAR above) exits with a non-zero status.
```

Yes, I have been able to compile your sources, with some modifications for trivial things like a couple of hard-coded paths, etc. Nothing major. I'm currently in the process of updating of my Android SDK and NDK, then I'll do a rebuild and look at merging this into Dante (_possibly_ with GNU Autoconf/Automake, depending on how much time and effort I'm able to put into this in the immediate future.)

I absolutely want to get rid of SCons; it's a terrible build system.

**Comment by kkszysiu** [comment]
Do you think that Autoconf/Automake is better solution?

**Comment by omcfadde** [comment]
Yes, I do, and this may just be because I'm more familiar with GNU tools and find them easier to use.

It's not my intention to start a build system argument, but if I can do something easier with GNU Autoconf/Automake than with SCons, I'm going to use the GNU tools.

**Comment by havlenapetr** [comment]
Hi, do you know what this error means, please:

---------- R_GLSL_Init ----------
I/Doom    (22202): Not available.
I/Doom    (22202): ----- R_ReloadGLSLPrograms -----
I/Doom    (22202): gl2progs/interaction.vert
I/Doom    (22202): 
I/Doom    (22202): gl2progs/interaction.frag
I/Doom    (22202): 
I/Doom    (22202): TODO: Sys_SetClipboardData
I/Doom    (22202): ********************
I/Doom    (22202): ERROR: R_LinkGLSLShader: program failed to link
I/Doom    (22202): 
I/Doom    (22202): ********************
E/Doom    (22202): Error during initialization

i have yours gl2progs/ in base dir and it looks like everything works, except: glGetProgramiv(shaderProgram->program, GL_LINK_STATUS, &linked); because linked is 0

**Comment by omcfadde** [comment]
Please run again with `+set developer 1' so that I may see the shader compiler messages.

Please also open your own bug here on the issue tracker. You are using the Android version, but this is a separate issue.

**Comment by kkszysiu** [comment]
Ok guys, no hardcoded paths anymore :) I fixed it in my latest commit.

**Comment by havlenapetr** [comment]
sorry, issue #17

**Comment by kkszysiu** [comment]
omcfadde, do you have any idea how to make virtual joystick in idTech4/OpenGL ES 2.0? Do I need to write own shader to archieve it?

To be honest I'm not so much experienced with OpenGL ES 2.0. I was working with OpenGL ES 1.0 but 2.0 and whole shaders is a new thing for me...

**Comment by omcfadde** [comment]
Well, no, a GLSL shader is not needed. I had some idea to have a circular area on the left and right bottom corners of the screen which would basically function like the analog sticks on game console controllers. Add some buttons along the top or bottom of the screen for weapon selection. This is stuff that would be done in game code and/or by editing the *.gui files. You might also need a material shader (Doom 3 material shader, not GLSL) and a texture for your virtual analog sticks.

If you want something quick and easy, you could use the accelerometer (tilt forward to move forward, back to move back, angle left/right to strafe left/right) aiming/shooting could be done on the touchscreen. I don't think this is a really good solution, because I did something similar for Maemo Quake 3. It worked, but it's not a great experience.

Third option is a tablet stand and Bluetooth controller (PS3 DualShock works nicely with Linux, shouldn't be _too_ much trouble with Android.)

Really input on mobile devices is not a solved problem. It's a difficult problem...

**Comment by omcfadde** [comment]
Oh, and I promise to try to get the Android work from kkszysiu merged into Dante during the weekend. Hopefully. Real life often makes other plans...

**Comment by kkszysiu** [comment]
I already implemented accelerometr solution. Will commit it soon but as you said it's not the best idea to control movements using accelerometer.

The best solution will be on OVUA console propably (if performace will be good enough) :D
Bluetooth joystick or keyboard/mouse will be good suited here too I think. Sadly I don't any of those things yet :)

**Comment by havlenapetr** [comment]
you can use keyboard and mouse via usb host feature. I've tested my build on i9000(1GHz CPU, PowerVR GPU, 512MB RAM shared with GPU) and fps is about 10-15frames per second, which is pretty low:-) maybe we should start working on optimalizations(SIMD ...), I know that on tablets and highend phones fps will be better, but I don't know how much better. And I don't understand why is this engine so slow against quake 3 arena engine, which is pretty fast. What is causing this low fps (bigger assets?), because source code is very similar to quake 3 arena. I will upload demo video tomorow. BTW I've started working on OpenSL audio driver, maybe tomorow I will be able to publish it

**Comment by kkszysiu** [comment]
Which level youre loading? test_box one?

**Comment by kkszysiu** [comment]
Well Quake 3 engine is faster because it doesnt used shaders, lights etc, that's why it's faster. Models have higher quality in Doom 3 too, engine is simillar from common side but whole graphics stuff is rewritten to meet 2004 year requirements.

**Comment by kkszysiu** [comment]
Maybe try our build, you should get better performance I think :) I have simillar hardware (My GPU is Adreno 205) and I have around 30 fps on test_box map.

**Comment by omcfadde** [comment]
Quake 3 is doing almost nothing in the vertex and fragment shaders; it doesn't use the programmable pipeline. Doom 3 makes extensive use of the GPU, in fact off-loading as much work as possible to the GPU. This is the primary reason for the performance difference, not the assets. Simply put, Doom 3 is performing more calculations per vertex and fragment.

You may gain some more performance by reducing the precision statements, but be very careful with the matrices. I would keep the MVP at highp and default everything to mediump. Vertex color attributes could possibly be reduced to lowp.

Of course this depends on the hardware. Imagination SGX may give totally different results than Nvidia Tegra when reducing the precision. There is also a divide in the vertex shader to convert the vertex color from 0-255 range into 0-1 range. This could be done on the CPU.

**Comment by havlenapetr** [comment]
ok, thanks for info (I am not very familiar with GL stuff), I've found this: http://developer.apple.com/library/ios/#documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/BestPracticesforShaders/BestPracticesforShaders.html#//apple_ref/doc/uid/TP40008793-CH7-SW3, there is some info about colors and lowp (how you wrote) in shaders. 10-15fps I am getting in menu, I don't know if your GNU build could be faster, I think that we should have same fps, because we are both building same source code with probably same optimizations. Are you building armv-7-neon build or just armv6 version? Where I can get test_box map, please?

**Comment by kkszysiu** [comment]
My build have hardcoded setting to always load test_box map, I changed common->Init method to this one:

common->Init(0, NULL, "+devmap testmaps/test_box");

**Comment by havlenapetr** [comment]
I am using standart common->Init(0, NULL, NULL) calling, but where I can get test_box file? I don't have it in my datas

**Comment by kkszysiu** [comment]
Are you using original Doom 3 paks? If yes, then you should have it.

**Comment by kkszysiu** [comment]
BTW on test_box map I have 26-30 fps without much FPS drops.

**Comment by kkszysiu** [comment]
Ok, really simple movement system using accelerometer implemented - forward and backward for now...

**Comment by havlenapetr** [comment]
I don't have test_box map in my assets, so I can't test test_box map right now, here is demo video: https://plus.google.com/photos/101582304371073858214/albums/5774194308102696945 (sometimes I have problem with colors and alpha like on video, but in most startups everything is correct, i don't know why this is happening sometimes)

**Comment by omcfadde** [comment]
havlenapetr, it's possible, though unlikely, that your _*.pk4_ files were corrupted during transfer. The only reason I suggest this is because it actually happened to me on my Galaxy Tab. I couldn't figure out why I would receive an error regarding "Couldn't load ... for player_model" (quoting from memory.)

It turned out, that for whatever reason, `adb push`-ing each of the _*.pk4_ files to the SD card again resolved the problem. It's a bit of a wild guess, but maybe you can try it.

Make sure you're executing the command `+devmap testmaps/test_box` because using `+devmap test_box` won't work.

**Comment by havlenapetr** [comment]
Can I ls installed maps somehow?

**Comment by kkszysiu** [comment]
I don't know it is possible from game but you can open your pak000.pk4 in winrar or different archiver then look at /maps/testmaps.

**Comment by havlenapetr** [comment]
I've commited my doom3 port: https://github.com/havlenapetr/adoom3 and here is audio driver: https://github.com/havlenapetr/adoom3/blob/master/jni/audio.cpp it needs some rework, now plays ugly sounds :-) probably it should be rewritten into async callback OpenSL style

**Comment by kkszysiu** [comment]
Ok, I will look into your audio implementation and fix what's possible. I'm quite experienced with OpenSL because I needed to rewrite my Uplink port audio to OpenSL.

**Comment by havlenapetr** [comment]
ok, I saw OpenSL for first time today:-)

**Comment by havlenapetr** [comment]
Just for info, I've wrote android project on top of idtech4 engine, so this is engine repo: https://github.com/havlenapetr/idtech4 and here is android project: https://github.com/havlenapetr/adoom3. I didn't want to put all android xmls, eclipse files and others into idtech4 engine project, I've wanted to have clean engine project with clean android project :-)

**Comment by havlenapetr** [comment]
so i've found that i have test_box map, but I am getting this:

I/Doom    ( 1415): [Load AAS]
I/Doom    ( 1415): loading maps/testmaps/test_box.aas48
I/Doom    ( 1415): WARNING: Couldn't load AAS file: 'maps/testmaps/test_box.aas48'
I/Doom    ( 1415): [Load AAS]
I/Doom    ( 1415): loading maps/testmaps/test_box.aas96
I/Doom    ( 1415): WARNING: Couldn't load AAS file: 'maps/testmaps/test_box.aas96'
I/Doom    ( 1415): [Load AAS]
I/Doom    ( 1415): loading maps/testmaps/test_box.aas_guardian
I/Doom    ( 1415): WARNING: Couldn't load AAS file: 'maps/testmaps/test_box.aas_guardian'
I/Doom    ( 1415): [Load AAS]
I/Doom    ( 1415): loading maps/testmaps/test_box.aas_mancubus
I/Doom    ( 1415): WARNING: Couldn't load AAS file: 'maps/testmaps/test_box.aas_mancubus'
I/Doom    ( 1415): [Load AAS]
I/Doom    ( 1415): loading maps/testmaps/test_box.aas_sabaoth
I/Doom    ( 1415): WARNING: Couldn't load AAS file: 'maps/testmaps/test_box.aas_sabaoth'
I/Doom    ( 1415): [Load AAS]
I/Doom    ( 1415): loading maps/testmaps/test_box.aas_cyberdemon
I/Doom    ( 1415): WARNING: Couldn't load AAS file: 'maps/testmaps/test_box.aas_cyberdemon'
I/Doom    ( 1415): Entering doom_main()

and .aas48 and aas96 I have there

**Comment by omcfadde** [comment]
havlenapetr, this is normal for testmaps/test_box; it doesn't include any AAS data.

Btw, I have setup an IRC channel on _irc.freenode.net_, _#dante_. I think this might be an easier solution for support than the issue tracker...

**Comment by havlenapetr** [comment]
ok, I agree :-)

**Comment by omcfadde** [comment]
Since we've now merged the initial support for Android into Dante, I'm going to close this issue to avoid it becoming a general "all things Android" issue. I'll open up a few more issues such as performance and audio support. Let's keep the discussions going! :-)
